# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: true
dist: trusty
cache: packages
latex: false
fortran: true
warnings_are_errors: false

r_packages:
- abind
- deldir

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libgsl0-dev bwidget
  - Rscript -e 'update.packages(ask = FALSE)'

install: 
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-5 90

after_success:
  - Rscript -e 'covr::codecov(branch = "develop")'

notifications:
  email:
  on_success: change
on_failure: change
