# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
sudo: true
dist: trusty
cache: packages
latex: false
fortran: true
warnings_are_errors: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"rce curl

r_packages:
- abind
- deldir

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev libgsl0-dev bwidget
  - Rscript -e 'update.packages(ask = FALSE)'

after_success:
  - Rscript -e 'covr::codecov(branch = "develop")'

notifications:
  email:
  on_success: change
on_failure: change
